services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.11
    container_name: nginx-proxy
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html

    networks:
      - proxy

  acme-companion:
    image: nginxproxy/acme-companion:2.6
    container_name: nginx-proxy-acme
    restart: unless-stopped

    environment:
      DEFAULT_EMAIL: jonathan.varild@gmail.com
      NGINX_PROXY_CONTAINER: nginx-proxy

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh

    networks:
      - proxy

networks:
  proxy:
    name: dd2482-proxy

volumes:
  certs:
  html:
  acme:
